# Use postgres/example user/password credentials
version: '3.2'

services:

  postgres:
    image: postgres:12.13
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  data:
    driver: local